version: '3.9'

services:
  db:
    build:
      context: ./db
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: "ec2-18-224-32-188.us-east-2.compute.amazonaws.com"
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "4000:80"
    depends_on:
      - backend