CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS shop;

GRANT ALL PRIVILEGES ON shop.* TO 'root'@'%';

FLUSH PRIVILEGES;